version: 1.2
tools:
  - name: ssips-uploader
    subclass: CWL
    primaryDescriptorPath: /sounder_sips/utils/dapa_download.cwl
    authors:
        - name: Wai PHyo
          email: makesuretofilloutanactualemailaddress@ucsc.edu
  - name: ssips-downlaoder
    subclass: CWL
    primaryDescriptorPath: /sounder_sips/utils/dapa_upload.cwl
    authors:
        - name: Wai Phyo
          email: anotherpersonsemailaddress@ucsc.edu
